#! /bin/sh

# Wallpaper
nitrogen --restore &

# Hotkeys + keyboard shortcuts
preg sxhkd || sxhkd &

# ==> START bspwm rules

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 28

# music apps on desktop 6
bspc rule -a Lollypop desktop='^6'
bspc rule -a QuodLibet desktop='^6'
bspc rule -a plasmawindowed desktop-'^6'
bspc rule -a Pavucontrol desktop='^6' state=floating

# other apps on defined desktops
bspc rule -a Opera desktop='^5' follow=off focus=off
bspc rule -a Gwe desktop='^7' follow=off focus=off
bspc rule -a GitKraken desktop='^7' follow=off focus=off
bspc rule -a code-oss desktop='^9' follow=off focus=off
bspc rule -a discord desktop='^8' follow=off focus=off
bspc rule -a Signal desktop='^8' follow=off focus=off

# floating apps
bspc rule -a jetbrains-studio state=floating
bspc rule -a "firefox":Toolkit state=floating sticky=on

# ==> END bspwm rules

# DWM swallow
pgrep bspswallow || $HOME/SYGtech/goteki-git/bspswallow/bspswallow &

# Compositor
pgrep picom || picom --experimental-backends &

# Polybar
pgrep polybar || $HOME/.config/polybar/polybar.sh &

# Nvidia
nvidia-settings --config="~/.config/nvidia/settings" --load-config-only
nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1

# Set RGB lights
ckb-next --background &
# openrgb --startminimized &

# Startup programs on desktop 1
cool-retro-term -e ~/.config/bspwm/tmux.sh &
sleep 1
bspc node -d ^10
sleep 5
cool-retro-term -e tmux attach-session -t Singular-1 &
#sleep 1
#cool-retro-term -e bashtop &

# Notifications
pgrep dunst || dunst -conf ~/.config/dunst/dunstrc &

# Fix for some Java programs
wmname LG3D

# Discord status
systemctl --user start discordrp-mpris.service

# Gnome polkit
pgrep polkit-gnome || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
