#! /bin/sh

wal -i $HOME/Pictures/Wallpapers/tokyolovestory.png &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
#bspc config normal_border_color "#e400d3"
bspc config window_gap           15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 28

bspc rule -a Lollypop desktop='^6'
bspc rule -a plasmawindowed desktop-'^6'
bspc rule -a Pavucontrol desktop='^6'

bspc rule -a Opera desktop='^5'

bspc rule -a Gwe desktop='^7' follow=off focus=off

# Polybar
$HOME/.config/polybar/polybar.sh &

killall -q compton
compton --config $HOME/.config/compton/config &

# Nvidia
nvidia-settings --load-config-only
nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
gwe --hide-window &
sleep 5
killall -q gwe

# Misc. applications
#plasmawindowed org.kde.plasma.mediacontroller &
killall -q ckb-next
ckb-next &
