#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 20

bspc rule -a Lollypop='^6'
bspc rule -a Opera='^5'

# Dartegnian
wal -i $HOME/Pictures/Wallpapers/rainykorea.jpg &
$HOME/.config/polybar/dartegnians_polybar.sh &

killall -q compton
compton --config $HOME/.config/compton/config &

# Nvidia
nvidia-settings --load-config-only
nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
gwe --hide-window &
sleep 5
killall -q gwe
