#! /bin/sh

# Wallpaper and Pywal
set_wallpaper_and_colors() {
	nitrogen --restore &
	zsh -ic gen-wal &
	source "${HOME}/.cache/wal/colors.sh"
}

# ==> START bspwm rules
configure_bspwm() {
	bspc monitor -d I II III IV V VI VII VIII IX X

	bspc config border_width				0
	bspc config window_gap					20
	bspc config split_ratio					0.5
	bspc config borderless_monocle				true
	bspc config gapless_monocle				true
	bspc config top_padding					46
	bspc config presel_feedback_color			"$color6"

	# music apps on desktop 6
	bspc rule -a Lollypop desktop='^6'
	bspc rule -a QuodLibet desktop='^6'
	bspc rule -a plasmawindowed desktop-'^6'
	bspc rule -a "Alacritty":ncmpcpp desktop='^6'
	bspc rule -a "Alacritty":miniplayer desktop='^6'
	bspc rule -a Pavucontrol desktop='^6' state=floating

	# other apps on defined desktops
	bspc rule -a Opera desktop='^5' follow=off focus=off
	bspc rule -a Nitrogen desktop='^5' follow=off focus=off
	bspc rule -a Gwe desktop='^7' follow=off focus=off
	bspc rule -a GitKraken desktop='^7' follow=off focus=off
	bspc rule -a WindowsVM desktop='^7' follow=off focus=off
	bspc rule -a discord desktop='^8' follow=off focus=off
	bspc rule -a Signal desktop='^8' follow=off focus=off
	bspc rule -a code-oss desktop='^9' follow=off focus=off
	bspc rule -a VSCodium desktop='^9' follow=off focus=off
	bspc rule -a Google-chrome-beta desktop='^2' follow=off focus=off

	# floating apps
	bspc rule -a jetbrains-studio state=floating
	bspc rule -a "firefox":Toolkit state=floating sticky=on

	# tiled apps
	bspc rule -a Zathura state=tiled
}

init_tiling_tools() {
	# DWM swallow
	pgrep -x bspswallow > /dev/null || $HOME/SYGtech/goteki-git/bspswallow/bspswallow &

	# Compositor
	pgrep -x picom > /dev/null || picom --experimental-backends &

	# Polybar
	pgrep -x polybar > /dev/null || $HOME/.config/polybar/polybar.sh &

	# Hotkeys + keyboard shortcuts
	pgrep -x sxhkd > /dev/null || sxhkd &

	# Notifications
	pgrep -x dunst > /dev/null || dunst -conf ~/.config/dunst/dunstrc &

	# Fix for some Java programs
	wmname LG3D
}

# Nvidia
configure_nvidia_gpu() {
	nvidia-settings --config="~/.config/nvidia/settings" --load-config-only
	nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
}

# Set RGB lights
init_rgb_trash() {
	ckb-next --background &
	pgrep -x openrgb > /dev/null || openrgb --startminimized -p Blue.orp &

	sleep 4
	killall -q openrgb
}

# Run tmux restore script on first login
restore_terminals() {
	if [[ -z $(pgrep tmux) ]]; then
		sh ~/.config/bspwm/tmux-startup.sh &
		sleep 1
	fi
	if [[ -n $(pgrep tmux) ]]; then
		sh ~/.config/bspwm/tmux-terminals.sh &
	fi
}

# MPD
init_mpd_utils() {
	pgrep -x mpd > /dev/null || systemctl start --user mpd
	pgrep -x playerctld > /dev/null || playerctld daemon
	pgrep -af mpDris2 > /dev/null || systemctl start --user mpDris2
}

# Polkit
init_gnome_polkit() {
	pgrep -x polkit-gnome > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
	gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
}

# Show Windows 8 start screen on login
show_start_screen() {
	sleep 2
	rofi -show drun
}

main() {
	set_wallpaper_and_colors
	configure_nvidia_gpu
	configure_bspwm
	init_tiling_tools
	init_mpd_utils
	init_gnome_polkit
	restore_terminals
	init_rgb_trash
	#show_start_screen
}

main
