#! /bin/sh

# Wallpaper and Pywal
function set_wallpaper_and_colors() {
	nitrogen --restore &
	zsh -ic gen-wal &
	source "${HOME}/.cache/wal/colors.sh"
}

# ==> START bspwm rules
function configure_bspwm() {
	bspc monitor HDMI-2 -d 1 2 3 4
	bspc monitor HDMI-1 -d 5 6 7 8 9 0
#	bspc monitor -d I II III IV V VI VII VIII IX X

	bspc config border_width				0
	bspc config window_gap					20
	bspc config split_ratio					0.5
	bspc config borderless_monocle				true
	bspc config gapless_monocle				true
	bspc config top_padding					30
	bspc config presel_feedback_color			"$color6"
#	bspc config border_radius				12

	# music apps on desktop 4
	bspc rule -a Lollypop desktop='^4'
	bspc rule -a QuodLibet desktop='^4'
	bspc rule -a deezer-enhanced desktop='^4'
	bspc rule -a Spotify desktop='^4'
	bspc rule -a plasmawindowed desktop='^4'
	bspc rule -a "Alacritty":ncmpcpp desktop='^4'
	bspc rule -a "Alacritty":miniplayer desktop='^4'
	bspc rule -a Pavucontrol desktop='^6' sticky=on state=floating

	# other apps on defined desktops
	bspc rule -a Opera desktop='^3' follow=off focus=off
	bspc rule -a Nitrogen desktop='^3' follow=off focus=off
	bspc rule -a protonmail-bridge desktop='^3' follow=off focus=off
	bspc rule -a thunderbird desktop='^7' follow=off focus=off
	bspc rule -a Gwe desktop='^7' follow=off focus=off
	bspc rule -a GitKraken desktop='^3' follow=off focus=off
	bspc rule -a WindowsVM desktop='^7' follow=off focus=off
	bspc rule -a discord desktop='^8' follow=off focus=off
	bspc rule -a Signal desktop='^8' follow=off focus=off
	bspc rule -a code-oss desktop='^9' follow=off focus=off
	bspc rule -a VSCodium desktop='^9' follow=off focus=off
	bspc rule -a Google-chrome-beta desktop='^2' follow=off focus=off

	# floating apps
	bspc rule -a "An Anime Game Launcher" state=floating
	bspc rule -a genshinimpact.exe state=floating
	bspc rule -a jetbrains-studio state=floating
	bspc rule -a '*:*:Picture in picture' state=floating sticky=on
	bspc rule -a "firefox":Toolkit state=floating sticky=on
	bspc rule -a Origin.exe floating=on
	bspc rule -a lofi state=floating center=on
	bspc rule -a mpv state=floating center=on sticky=on
	bspc rule -a zoom state=floating center=on
	bspc rule -a steam state=floating
	bspc rule -a steamwebhelper state=floating
	
	# full screen apps
	#bspc rule -a steamwebhelper state=fullscreen center=on

	# tiled apps
	bspc rule -a Zathura state=tiled
	
	# sticky apps
	bspc rule -a "scrcpy" state=floating sticky=on
}

function init_tiling_tools() {
	# DWM swallow
	pgrep -x bspswallow > /dev/null || $HOME/SYGtech/goteki-git/bspswallow/bspswallow &

	# Hotkeys + keyboard shortcuts
	pgrep -x sxhkd > /dev/null || sxhkd &

	# Notifications
	pgrep -x dunst > /dev/null || dunst -conf ~/.config/dunst/dunstrc &

	# Polybar
	pgrep -x polybar > /dev/null || $HOME/.config/polybar/polybar.sh &

	# Fix for some Java programs
	wmname LG3D
}

# Nvidia
function configure_nvidia_gpu() {
	nvidia-settings --config="~/.config/nvidia/settings" --load-config-only
	nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
	nvidia-settings -a 'AllowFlipping=0'
	sh ~/SYGtech/goteki-git/shell-scripts/force_full_composition_pipeline.sh
}

# Set RGB lights
function init_rgb_trash() {
	ckb-next --background &
	pgrep -x openrgb > /dev/null || openrgb --startminimized -p TVA.orp &

	sleep 4
	killall -q openrgb
}

# Run tmux restore script on first login
function restore_terminals() {

	if [[ -z $(pgrep tmux) ]]; then
		sh ~/.config/bspwm/tmux-startup.sh &
		sleep 1
	fi
	if [[ -n $(pgrep tmux) ]]; then
		sh ~/.config/bspwm/tmux-terminals.sh &
	fi
}

# MPD
function init_mpd_utils() {
	pgrep -x mpd > /dev/null || systemctl start --user mpd
	pgrep -x playerctld > /dev/null || playerctld daemon
	pgrep -af mpDris2 > /dev/null || systemctl start --user mpDris2
}

# Polkit
function init_gnome_polkit() {
	pgrep -x polkit-gnome > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
	gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
}

function run_misc_programs() {
	# Compositor
	pgrep -x picom > /dev/null || picom &

	protonmail-bridge --no-window &
	sleep 10
	birdtray &
}

# Show Windows 8 start screen on login
function show_start_screen() {
	sleep 2
	rofi -show drun
}

function main() {
	set_wallpaper_and_colors
	configure_nvidia_gpu
	configure_bspwm
	init_tiling_tools
	restore_terminals
	init_mpd_utils
	init_gnome_polkit

	init_rgb_trash
	run_misc_programs
	#show_start_screen
}

main
