#!/bin/sh
# Xsetup - run as root before the login dialog appears
#xrandr -s 1920x1080
xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output HDMI-2 --mode 1366x768 --rotate normal --above HDMI-1
