#! /bin/sh

sxhkd &

bspc monitor eDP -n 0 -d I II III IV V
bspc monitor HDMI-A-0 -n 1 -d VI VII VII IX X


bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config top_padding 0

bspc config -m 1 top_padding 0
bspc config -m 0 top_padding 20

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Tilda desktop='6' state=fullscreen follow=off

# Dartegnian's modifications
$HOME/.config/polybar/dartegnians_polybar.sh &

killall -q compton
compton --config $HOME/.config/compton/config &

DRI_PRIME=1 feh --bg-fill ~/Pictures/pinkteal.jpg --bg-fill ~/Pictures/tealpink.jpg &