#! /bin/sh

# Wallpaper
nitrogen --restore &

# Hotkeys + keyboard shortcuts
sxhkd &

# ==> START bspwm rules

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
#bspc config normal_border_color "#e400d3"
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 28

# music apps on desktop 6
bspc rule -a Lollypop desktop='^6'
bspc rule -a QuodLibet desktop='^6'
bspc rule -a plasmawindowed desktop-'^6'
bspc rule -a Pavucontrol desktop='^6'

# other apps on defined desktops
bspc rule -a Opera desktop='^5'
bspc rule -a Gwe desktop='^7' follow=off focus=off

# ==> END bspwm rules

# Compton
killall -q compton
compton --config $HOME/.config/compton/config &

# Polybar
$HOME/.config/polybar/polybar.sh &

# Nvidia
nvidia-settings --load-config-only
nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1

# Set RGB lights
ckb-next &
sleep 0.5
xdo close -n ckb-next &

# Startup programs on desktop 1
cool-retro-term -e ~/.config/bspwm/tmux.sh &
sleep 0.3
cool-retro-term -e gotop &
sleep 0.3
alacritty -e cava &
plasmawindowed org.kde.plasma.mediacontroller &

# Notifications
dunst -conf ~/.config/dunst/dunstrc &

# VPN
mullvad-vpn &

