#! /bin/sh

# Wallpaper
nitrogen --restore &

# Hotkeys + keyboard shortcuts
sxhkd &

# ==> START bspwm rules

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 28

# music apps on desktop 6
bspc rule -a Lollypop desktop='^6'
bspc rule -a QuodLibet desktop='^6'
bspc rule -a plasmawindowed desktop-'^6'
bspc rule -a Pavucontrol desktop='^6'

# other apps on defined desktops
bspc rule -a Opera desktop='^5'
bspc rule -a Gwe desktop='^7' follow=off focus=off
bspc rule -a GitKraken desktop='^7'
bspc rule -a code-oss desktop='^9'

# floating apps
bspc rule -a jetbrains-studio state=floating
bspc rule -a "Katawa Shoujo" state=floating
bspc rule -a katawashoujo_actual_1.3 state=floating

# ==> END bspwm rules

# Compositor
picom --experimental-backends &

# Polybar
$HOME/.config/polybar/polybar.sh &

# Nvidia
nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only
nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1

# Set RGB lights
ckb-next &
sleep 0.5
xdo close -n ckb-next &
sleep 0.5

# Startup programs on desktop 1
cool-retro-term -e ~/.config/bspwm/tmux.sh &
sleep 0.5
bspc node -d ^10
sleep 4
cool-retro-term -e tmux attach-session -t Singular-1 &
sleep 1
cool-retro-term -e bashtop &
# sleep 1
# alacritty -e cava &
sleep 0.5
cool-retro-term -e alsamixer -D hw:3 &
sleep 1
sleep 0.5
bspc node -z top 0 40

# Notifications
dunst -conf ~/.config/dunst/dunstrc &

# Fix for some Java programs
wmname LG3D

# Discord status
systemctl --user start discordrp-mpris.service
